apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgBTgpRgPFZ5aRxw18WvzVRQy7345gm2zhzl3ozZn7Gzstgxo9H2m7vkJpHx216OQJk9uB1BqSDegP5km2bUB0As45I/H02XzCKqOhLo46LCMc2Ht5Xv5/sbssdlioc0auQd7N6Uccb+NDBgi2ZPJ2KZiDYroenGW6kD3Z+5UEGX9kC9kim/DFK2qtVcOd5PAqSR0JyGE6t3ynq+W4f/Koqm03z7ukYqaK+fxzoJzm13MChz0H3G1tK7FQCHdjPXj18BxueRqN54FkyVpNxHYZnXBljQwe8qmQM39ossKQReeVmosSJKYwGfWq3VbZPm6apKvXQwizaLqKyPephDT1ZeK2yJz1u3IJN7XYp4e5uNLosGUQ48EV1a+t+wSlcCZ+F0Y2DK1GSvmexNeL0iw64R4jJN/fL64yj3mMNSmK0CiN62XHbXuxogdfP64z6fIdW/DL378Qt4x3/N524ebAtXv8A6zwnfJ2cclE4aTWyt56TPjFZAXpgLWAobNdfnaEG7m8KhvzpXQuQZ3KEz6qcRS0flPIknYxTDbIEk6eikGVvlJaG4cx3s5qvWHK2VlzDa0T2qDy2h1tbL6Pby3wjl2FAG0qb4T09cuP4kT8gVPsJswABXD/RfjQc28bwNHzmlTuTPdYUoku/+HX/ssxNL03IS/BCIu7Dk0AmZKTSI27VvsE+53Bn+xzuK9Dl8E/Wog/s=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
status: {}

