apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgBEcA85YboqI9RIuuAgaVNZbtqgpNORO3j2st8w2s44JIeflMdzhtMzQukepN4GsA1BXTXXwWhbZ3nslPtuUVlAmWdTNw4iFu3SwsKZ5OLm4Z7j3/Y7HOjwx5UQ/ihW6qYVOGkDnpJ8c24f+18k1LjIMCnxhG7qUutcjk7jvkBxR4hF/0PJPriv0PHetdhiv0TkB1N4I/PEd5+neP2T/TkoBWBMCR5JlXJ2ywKoataYzH0U+MC8Ny4coJUCSLZN6xDJKfC8lMt+rq+IX/kIWXIVmuu4136ON6aT4Q7yDU5Axb7LOyGtRu2UMGsIwnqUeeBs9JOd+PiuE/amq82+KbNm0F/q3s8XDdpCHwt3sTqyQxvfAAeC9G7Fw0KFUJRs55c7rcjlmf7Jyc+w7yLZuvbsci5XS3cGF8u/xQkC8tFT1TiKU9gSkhCD8rcrmvhh/DhWdFOgT+IBRnem2uSQKkRyJdwBNjm5I8TmsjYxrOzs6MbVve+bZYQrwrSn3FxqIjkqb10U6OIjJTyZXwK9lrR0Ze+0kWWZiqAphcaSVDmmy5EOa9oI8X90xBOu/LK4GgNXY5xj+GFrcASUgc6+5UEsF00Qaf+fryXWKNxLS3df7oUKgmvXgY1V7F7NMp0N2CP2Jvx02Or1UpNCWEQ9zuEwtijcbv9yjZEnSh+3FZlVv636I/aaP8D1RXa8u8wBgcnBD7A=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
status: {}

